Fix: #10. Add security considerations.
ietf-wg-httpapi/mediatypes pull request #15
Opened 2022-01-26 11:32 UTC by ioggstream

## This PR

- adds yaml security considerations

## Note

- todo: add normative statements wrt using yaml as a more concise form for describing json objects

2022-01-28 17:56 UTC, perlpunk commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +- local tags such as `!!python/object` and
`!!python/object` is not a "local" tag. local tags only have one `!`. Maybe call it a "custom tag".

2022-01-31 14:49 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +- local tags such as `!!python/object` and
@perlpunk will this work?

```suggestion
- custom and local tags such as `!!python/object` and
```

2022-02-01 08:15 UTC, VladimirAlexiev commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +When using YAML as a more efficient format
`More user friendly` not `more efficient`

2022-02-01 11:07 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +When using YAML as a more efficient format
Reasonable, but we don't even need to investigate the motivations.

```suggestion
When using YAML
```

2022-02-07 11:45 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +that code execution would result to strictly bounded time/memory limits.
```suggestion
that code execution will result to strictly bounded time/memory limits.
```

2022-02-07 11:45 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +(e.g the `yaml.safe_load` function in `pyyaml`, ...).
```suggestion
(e.g. the `yaml.safe_load` function in `pyyaml`, ...).
```

2022-02-07 15:06 UTC, ingydotnet requested changes
I don't think this PR represents YAML well.

The issues should probably only be discussed in the abstract.

Also YAML is a versioned language that changes over time, so how will the mediatype account for that?

This review is far from complete, but I wanted to weigh in early.

2022-02-07 15:16 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +Since YAML [yaml] is a superset of JSON [JSON],
This doc refers to YAML 1.2.2

My understanding is that YAML usage in the API world heavily relies on YAML being a superset on JSON (aka a JSON document is a valid YAML document).

2022-02-07 15:27 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +this includes comments (see Section 3.2.3.3 of [yaml])
Referencing subsections is quite common in I-D, but I understand that - if you think specs are going to change - this can be suboptimal.

OTOH since this document is a draft:

0- `[yaml]` references 1.2.2 spec;
1- referencing specific sections helps reviewer in identifying parts of the spec they might not know (eg. it's ~10y that I use yaml but I just read the whole spec just recently;
2- we can remove section references before finalizing the document.

2022-02-07 15:35 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +In some cases an implementer can adopt a restricted YAML schema
> I wouldn't speak in specifics about tags and schemas.

Which drawbacks do you see in using these concepts to explain possible interoperability issues to implementers?
Is this because you are going to scratch/restructure them?

> Note that !!merge, !!set, !!map, !!pairs are not defined in the current spec.

I need to clarify that some of the language independent tags listed [here](https://yaml.org/type/)
are not part of YAML spec. Since they are widely used, I thought that providing them as an
example could be useful.

2022-02-07 15:39 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +~~~
```suggestion
```

2022-02-07 15:39 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +(e.g. the `yaml.safe_load` function in `pyyaml`, ...).
```suggestion
Many implementations provide safe deserializers addressing these issues.
```

2022-02-07 16:16 UTC, ingydotnet commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +In some cases an implementer can adopt a restricted YAML schema
Sorry, I meant `!!omap`, not `!!map`.

See: https://github.com/yaml/yaml-spec/issues/276
The tags are not in any 1.2.2 schema.
Also they are not commonly seen in my experience.

2022-02-07 16:39 UTC, ingydotnet commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +- mapping keys that are non-scalar or of non-JSON types (see Section 2.2 of [yaml]);
This should be `mapping keys that are not strings` since that's the only type allowed as a key by JSON.

2022-02-07 16:45 UTC, ingydotnet commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +YAML has some features like explicit typing (e.g. `!!omap`) and local tags that,
We say `explicit tagging`, not `explicit typing`.

I might just say something like:

> Care should be used when using YAML tags, as they have been tied to various code execution exploits in some YAML framework implementations.

2022-02-07 17:12 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +In some cases an implementer can adopt a restricted YAML schema
> Also they are not commonly seen in my experience.

I  was specifically referring to merge keys `<<:` , while you are right that `omap`, `set` & co are not very used.

2022-02-07 17:22 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +YAML has some features like explicit typing (e.g. `!!omap`) and local tags that,
> We say explicit tagging, not explicit typing.

Ok, just found that [here](https://github.com/yaml/yaml-spec/blame/main/spec/1.2.2/spec.md#L523) :P

> Care should be used ...

I'll try to refactor, but probably it is important to point out that code can be executed.
In my perspective this section is also targeted to yaml library implementers that need to prevent their users to unwillingly execute code.

2022-02-09 14:26 UTC, ioggstream commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +Since YAML [yaml] is a superset of JSON [JSON],
Updated references to 1.2.2.

> we can't say with 100% certainty that future versions will be

The Times, they are a-changin' :) We can update this section
when YAML changes. I tweaked the text a bit, though.

2022-02-09 16:47 UTC, ioggstream commented
Thanks @ingydotnet for your review.

> The issues should probably only be discussed in the abstract.
I made them more abstract, but since the text is for a broad audience of yaml
users, I think it is useful to provide some background.
 
> Also YAML is a versioned language that changes over time, so how will the mediatype account for that?
This is the same for every language: when JSON RFC was updated, [the media type registration note was changed too](https://www.iana.org/assignments/media-types/application/json). When the language change, the media type can be updated.
You do not necessarily require an RFC for that.

> This review is far from complete, but I wanted to weigh in early.
You did well. Consider that this is just the beginning of the process :)

2022-02-20 19:17 UTC, ioggstream commented
Since YAML is evolving, it can be valuable for implementers to explain that
in the internet you can find documents relying on 1.1 features like https://yaml.org/type/

2022-02-21 16:17 UTC, ioggstream reviewed
Some comments.

2022-02-25 13:35 UTC, eemeli approved these changes

2022-02-25 13:35 UTC, eemeli commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +some features have been added, and other removed.
```suggestion
some features have been added, and others removed.
```

2022-02-25 13:35 UTC, eemeli commented on draft-ietf-httpapi-rest-api-mediatypes.md
> +YAML documents are rooted, connected, directed graph
```suggestion
YAML documents are rooted, connected, directed graphs
```

2022-03-04 16:05 UTC, merged